[package]
name = "rle"
version = "0.2.0"
authors = ["elided for anonymous review"]
edition = "2021"
license = "ISC OR Apache-2.0"
description = "Simple utilities for run-length encoded data"

[dependencies]
smallvec = { version = "1.8.0", optional = true }
